import type { Metadata } from "next";
import "./globals.css";
import { Inter, Righteous } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { AppContextProvider } from "@/Context/AppContext";

// Initialize the font
const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-righteous",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${righteous.variable} ${inter.variable} `}>
      <body className="font-sans">
        <AppContextProvider>
          <Toaster />
          {children}
        </AppContextProvider>
      </body>
    </html>
  );
}
