import type { Metadata } from "next";
import "./globals.css";
import { Righteous } from "next/font/google";

// Initialize the font
const righteous = Righteous({
  weight: "400",
  subsets: ['latin'],
  variable: '--font-righteous',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${righteous.variable}`}>
      <body className="font-sans">
        {children}
      </body>
    </html>
  );
}